services:
  web:
    build: .
    container_name: home_automation
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    profiles: ["web"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      web-init:
        condition: service_completed_successfully

  web-init:
    build:
      context: .
    command: python manage.py migrate --noinput --skip-checks
    volumes:
      - .:/app
    profiles: ["web"]
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      - database

  database:
    image: postgres:15-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home_automation
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles: ["db", "web"]


volumes:
  db-data:
