[tool.poetry]
name = "home-automation-hub"
version = "0.1.0"
description = ""
authors = ["Robert Nyström <robert.nystrom@toolsense.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
python-dotenv = "^1.0.0"
psycopg = { extras = ["binary"], version = "3.1.16" }
gunicorn = "^21.2.0"
django-rest-framework = "^0.1.0"
django-cors-headers = "^4.3.1"
djangorestframework-stubs = "^3.14.5"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"
mypy = "^1.8.0"
django-stubs = "^4.2.7"

[tool.poetry.group.prod.dependencies]
psycopg = { extras = ["c"], version = "3.1.16" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]


[tool.django-stubs]
django_settings_module = "config.settings"
