[tool.poetry]
name = "home-automation-hub"
version = "0.1.0"
description = ""
authors = ["Robert Nyström <robert.nystrom@toolsense.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
python-dotenv = "^1.0.0"
psycopg = { extras = ["binary"], version = "3.1.16" }
gunicorn = "^21.2.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"

[tool.poetry.group.prod.dependencies]
psycopg = { extras = ["c"], version = "3.1.16" }


[tool.poetry.group.ci.dependencies]
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
