# Generated by Django 5.0 on 2024-01-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_splitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='excluded_amount',
        ),
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cost',
            name='included_in_report',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_splitter.costsplitreport'),
        ),
    ]
