# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Tests & Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build the docker-compose stack
      run: docker-compose up -d backend-timescale backend-redis rollout-db

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v2

    - name: Setup virtual environment & Dependencies
      run: rye sync

    - name: Code style & lint check
      run: make check

    - name: Code Static Analysis
      run: make types

    - name: Run Migrations
      run: poetry run python manage.py migrate

    - name: Test & Coverage
      run: make coverage
