# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Tests & Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build the docker-compose stack
      run: docker compose --profile db up --build -d

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v2

    - name: Setup virtual environment & Dependencies
      run: rye sync

    - name: Code style & lint check
      run: make check

    - name: Code Static Analysis
      run: make types

    - name: Run Migrations
      run: rye run python manage.py migrate

    - name: Test & Coverage
      run: make coverage
